Math magic test
Bushido-brown/math-magic pull request #6
Opened 2022-07-07 14:52 UTC by Bushido-brown

Wrote unite test to test components of the calculator

2022-07-07 15:21 UTC, roshan-bajgain requested changes
Hi @Bushido-brown, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️
- Professional README file. ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-07 15:21 UTC, roshan-bajgain commented on src/__test__/App.test.js
> +});
- [ ] Your test is not passed as it is throwing an error kindly fix it.
### Error
![hiss](https://user-images.githubusercontent.com/81727988/177809699-def0f94d-b81f-4af8-b8cb-5cbeaa02893a.png)

2022-07-07 15:21 UTC, roshan-bajgain commented on src/logic/___tests___/calculate.test.js
> +  });
- [ ] Kindly write the test for operate.js in a different file for better practice

2022-07-09 18:53 UTC, EricMbouwe approved these changes
Hi @Bushido-brown, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Linters ok
- PR ok
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-08 10:09 UTC, merged